### ISSUE TITLE
The command line description is repeated

### ISSUE THREAD

**Issue by Me19m4** [sec-tools/litefuzz#1]
There are two duplicated descriptions on the command line in the README

` -x MAXTIME, --maxtime MAXTIME
                        **timeout for the run** (default: 1)
  --mutator MUTATOR, --mutator MUTATOR
                        **timeout for the run** (default: 0=random)`

**Comment by sec-tools** [comment]
hey @MoqiGod, this is how argparse is displaying the argument names, -x/--maxtime both mapping to the timeout and --mutator (with no given short flag) mapping to mutation selection. So while not ideal, there's just so many flags and only so many letters, it's intended.

thanks!
